version: '3'
services:
    nginx:
        platform: linux/arm64/v8
        container_name: nginx-surplus-id
        image: nginx:1.17.8
        command: [ "nginx", "-g", "daemon off;" ]
        depends_on:
            - app
        links:
            - app
        working_dir: /var/www/html
        volumes:
            - ./docker/nginx/asset/:/etc/nginx/conf.d/
            - ./docker/nginx/log:/var/log/nginx/:rw
            - ./:/var/www/html:rw
        ports:
            - "${DOCKER_NGINX_PORT:-8000}:80"
        logging:
            options:
                max-size: "1m"
                max-file: "3"
        networks:
            - surplus-id-network
    app:
        container_name: app-surplus-id
        build: ./docker/php
        working_dir: /var/www/html
        links:
            - db
        depends_on:
            - db
        volumes:
            - ./:/var/www/html:rw
        command: bash -c "php-fpm"
        logging:
            options:
                max-size: "1m"
                max-file: "3"
        networks:
            - surplus-id-network
    db:
        platform: linux/arm64/v8
        container_name: db-surplus-id
        image: "mysql:latest"
        volumes:
            - "./dbdata:/var/lib/mysql/"
        env_file:
            - ./docker/.env
        ports:
            - "${DOCKER_DB_PORT:-3307}:3306"
        networks:
            - surplus-id-network
    phpmyadmin:
        platform: linux/amd64
        container_name: phpmyadmin-surplus-id
        image: phpmyadmin/phpmyadmin
        env_file:
            - ./docker/.env
        ports:
            - "${DOCKER_DB_PANEL_PORT:-8082}:80"
        volumes:
            - /sessions
        networks:
            - surplus-id-network

networks:
    surplus-id-network:
